[tool.poetry]
name = "python-init"
version = "0.1.0"
description = ""
authors = ["tanar <takujump@gmail.com>"]

[tool.poetry.dependencies]
python = "3.9.13"
Django = "^4.0.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
